name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  compile:
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Install Dependencies
        run: dart pub get
      - name: Compile
        run: dart compile exe bin/alfred_jetbrains_cli.dart -o bin/alfred_jetbrains_cli
      - uses: actions/upload-artifact@v4
        with:
          name: alfred_jetbrains_cli
          path: bin/alfred_jetbrains_cli
          overwrite: true

  release:
    runs-on: macos-latest
    needs: [compile]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: alfred_jetbrains_cli
          path: bin
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/alfred_jetbrains_cli
          fail_on_unmatched_files: true
